### ISSUE TITLE
betting.active_fixtures endpoint - start_date field

### ISSUE THREAD

**Issue by BroomJack** [betcode-org/betconnect#26]
The start_date field has the time always as 00:00. There is argument that it is just for the date, but it is a datetime data type and I can't see the harm in having the time here as well. Yes, there is a 'time' value, but it would make things easier if the time was correct in start_date.
`[Fixture: Eintracht Frankfurt v West Ham(9050623) 2022-05-05 00:00:00, Fixture: Rangers v RB Leipzig(9050622) 2022-05-05 00:00:00]`
`fixture_id=9050623 display_name='Eintracht Frankfurt v West Ham' start_date=datetime.datetime(2022, 5, 5, 0, 0) time=datetime.time(20, 0) each_way_active=None`
^ As you can see in both these examples, the time is 00:00:00 which is just wrong

**Comment by varneyo** [comment]
Have you looked at ActiveFixture.start_date_time?

**Comment by BroomJack** [comment]
Didn't know about this field. When doing a print of the object, all I saw were the `start_date` and `time` values so didn't think to look for it.

**Comment by varneyo** [comment]
Cool, always best to use the debugger rather print stuff I find
