### ISSUE TITLE
my_bets Lay side bets validation errors

### ISSUE THREAD

**Issue by BroomJack** [betcode-org/betconnect#36]
We have a load of field validation on the response when you hit the `my_bets` endpoint in the API but if you pass it `my_bets/back` you'll get a response specific to bet_requests containing fields like `profit`, `matched_stake`, and `fill_percentage`. When you hit `my_bets/lay` you get fields specific to bets containing fields like `liability` and not those mentioned for bet_requests.

Issue here is that the field validation is used for both responses and the validation is back side specific so it fails on multiple fields when you try get your layside bets.

**Comment by jbeasley123** [comment]
Fixed in https://github.com/betcode-org/betconnect/pull/37
